/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    bookGenres: BookGenre;
    books: Book;
    authors: Author;
    bookChapters: BookChapter;
    posts: Post;
    readProgress: ReadProgress;
    chapterComments: ChapterComment;
    bookmarks: Bookmark;
    complaints: Complaint;
    reviews: Review;
    'user-uploads': UserUpload;
    notifications: Notification;
    wikiEntries: WikiEntry;
    wikiMentions: WikiMention;
    wikiRelations: WikiRelation;
    wikiIngestRuns: WikiIngestRun;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    books: {
      chapters: 'bookChapters';
    };
    authors: {
      books: 'books';
    };
    chapterComments: {
      children: 'chapterComments';
    };
    wikiEntries: {
      mentions: 'wikiMentions';
      outgoingRelations: 'wikiRelations';
      incomingRelations: 'wikiRelations';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    bookGenres: BookGenresSelect<false> | BookGenresSelect<true>;
    books: BooksSelect<false> | BooksSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    bookChapters: BookChaptersSelect<false> | BookChaptersSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    readProgress: ReadProgressSelect<false> | ReadProgressSelect<true>;
    chapterComments: ChapterCommentsSelect<false> | ChapterCommentsSelect<true>;
    bookmarks: BookmarksSelect<false> | BookmarksSelect<true>;
    complaints: ComplaintsSelect<false> | ComplaintsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'user-uploads': UserUploadsSelect<false> | UserUploadsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    wikiEntries: WikiEntriesSelect<false> | WikiEntriesSelect<true>;
    wikiMentions: WikiMentionsSelect<false> | WikiMentionsSelect<true>;
    wikiRelations: WikiRelationsSelect<false> | WikiRelationsSelect<true>;
    wikiIngestRuns: WikiIngestRunsSelect<false> | WikiIngestRunsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    banner: Banner;
  };
  globalsSelect: {
    banner: BannerSelect<false> | BannerSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  authStrategies?:
    | {
        providerUserId?: string | null;
        accessToken?: string | null;
        refreshToken?: string | null;
        tokenType?: string | null;
        idToken?: string | null;
        tokenExpiry?: string | null;
        authProvider?: 'google' | null;
        id?: string | null;
      }[]
    | null;
  nickname: string;
  roles: ('admin' | 'editor' | 'user' | 'supporter')[];
  bookAccess?: (string | Book)[] | null;
  avatar?: (string | null) | UserUpload;
  banner?: (string | null) | UserUpload;
  isPublic?: boolean | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books".
 */
export interface Book {
  id: string;
  _books_books_order?: string | null;
  _order?: string | null;
  title: string;
  alternativeNames?: string[] | null;
  status: 'ongoing' | 'completed' | 'hiatus' | 'cancelled';
  coverImage: string | Media;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Canonical facts about this book for the wiki ingest pipeline: protagonist name and aliases, what realms/ranks mean in this world, common naming pitfalls. Injected into the LLM prompt as-is.
   */
  wikiContext?: string | null;
  genres: (string | BookGenre)[];
  chapters?: {
    docs?: (string | BookChapter)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Volumes are used to group chapters. For example, a book can have multiple volumes, each containing a range of chapters.
   */
  volumes?:
    | {
        name: string;
        from: number;
        to: number;
        id?: string | null;
      }[]
    | null;
  author: string | Author;
  slug?: string | null;
  slugLock?: boolean | null;
  chapterCount?: number | null;
  averageRating?: number | null;
  totalReviews?: number | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookGenres".
 */
export interface BookGenre {
  id: string;
  title: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookChapters".
 */
export interface BookChapter {
  id: string;
  _bookChapters_chapters_order?: string | null;
  title: string;
  /**
   * Check this if the title contains spoilers.
   */
  isSpoiler?: boolean | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  addedAt?: string | null;
  book: string | Book;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: string;
  name: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  books?: {
    docs?: (string | Book)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-uploads".
 */
export interface UserUpload {
  id: string;
  owner: string | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  _order?: string | null;
  title: string;
  shortDescription: string;
  image: string | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  publishedAt: string;
  slug?: string | null;
  slugLock?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "readProgress".
 */
export interface ReadProgress {
  id: string;
  user: string | User;
  book: string | Book;
  chapter: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chapterComments".
 */
export interface ChapterComment {
  id: string;
  user: string | User;
  chapter: string | BookChapter;
  content: string;
  children?: {
    docs?: (string | ChapterComment)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  parent?: (string | null) | ChapterComment;
  breadcrumbs?:
    | {
        doc?: (string | null) | ChapterComment;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookmarks".
 */
export interface Bookmark {
  id: string;
  user: string | User;
  book: string | Book;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "complaints".
 */
export interface Complaint {
  id: string;
  selectedText: string;
  complaintType:
    | 'incorrect-translation'
    | 'grammatical-error'
    | 'terminology-inconsistency'
    | 'stylistic-issue'
    | 'missing-text'
    | 'other';
  description: string;
  pageNumber: number;
  chapter: string | BookChapter;
  book: string | Book;
  position?: {
    start?: number | null;
    end?: number | null;
  };
  status: 'pending' | 'reviewing' | 'resolved' | 'rejected';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: string;
  user: string | User;
  book: string | Book;
  content: string;
  rating: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: string;
  user: string | User;
  title: string;
  message?: string | null;
  type: 'info' | 'warning' | 'error';
  read?: boolean | null;
  link?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Entities extracted from chapters (characters, locations, items...). Spoiler gating is NOT enforced by access control — the frontend must filter by spoilerChapterIndex against reader progress.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wikiEntries".
 */
export interface WikiEntry {
  id: string;
  novel: string | Book;
  type: 'character' | 'location' | 'organization' | 'technique' | 'item' | 'realm' | 'event' | 'concept';
  title: string;
  slug: string;
  slugLock?: boolean | null;
  /**
   * Alternative names used in the text. The ingest pipeline matches new mentions against title + aliases before creating a new entry.
   */
  aliases?: string[] | null;
  image?: (string | null) | Media;
  /**
   * One-two sentences, spoiler-free if possible. Shown in lists, tooltips and link previews.
   */
  shortDescription?: string | null;
  /**
   * The pipeline generates Markdown and converts it via convertMarkdownToLexical (same as importChapters.ts).
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 1-based chapter number, same numbering as reader URLs and readProgress.
   */
  firstAppearanceIndex?: number | null;
  /**
   * The entry is safe for readers who reached this chapter number. Frontend filters: spoilerChapterIndex <= readProgress.chapter.
   */
  spoilerChapterIndex?: number | null;
  /**
   * The ingest pipeline must only overwrite entries with status "auto". Human-touched entries (review/published/hidden) are never rewritten by AI.
   */
  status: 'auto' | 'review' | 'published' | 'hidden';
  confidence?: number | null;
  /**
   * Model or script name that last generated this entry.
   */
  generatedBy?: string | null;
  /**
   * Pipeline bookkeeping: the entry reflects chapters up to this number.
   */
  lastProcessedChapterIndex?: number | null;
  /**
   * Flexible type-specific scalar details. Put cross-entry links into Wiki Relations instead.
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  mentions?: {
    docs?: (string | WikiMention)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  outgoingRelations?: {
    docs?: (string | WikiRelation)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  incomingRelations?: {
    docs?: (string | WikiRelation)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Evidence layer: one record per entity per chapter. The unique index (entry + chapterIndex + rawName) makes ingest re-runs idempotent — the pipeline should upsert.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wikiMentions".
 */
export interface WikiMention {
  id: string;
  novel: string | Book;
  entry: string | WikiEntry;
  chapter?: (string | null) | BookChapter;
  /**
   * 1-based chapter number, same numbering as reader URLs and readProgress. Used for spoiler gating and ordering.
   */
  chapterIndex: number;
  /**
   * The exact name or phrase used in the chapter text.
   */
  rawName: string;
  mentionType:
    | 'appearance'
    | 'dialogue'
    | 'backstory'
    | 'power-up'
    | 'relationship-change'
    | 'death'
    | 'item-acquired'
    | 'location-visited'
    | 'realm-change'
    | 'other';
  /**
   * Short source quote from the chapter.
   */
  quote?: string | null;
  /**
   * What this mention tells us about the entry.
   */
  context?: string | null;
  confidence?: number | null;
  approved?: boolean | null;
  source?: ('ai' | 'manual' | 'import') | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * One edge per fact. Every type has a single canonical direction — the inverse view comes from the incomingRelations join on the entry. For symmetric types (friend-of, sibling-of...) the pipeline must normalize direction (e.g. lower entry id as source) so A→B and B→A do not both get created.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wikiRelations".
 */
export interface WikiRelation {
  id: string;
  novel: string | Book;
  sourceEntry: string | WikiEntry;
  targetEntry: string | WikiEntry;
  /**
   * Canonical directions: teacher-of (not student-of), parent-of (not child-of). Symmetric: related-to, sibling-of, friend-of, enemy-of, ally-of, rival-of, romantic-interest-of.
   */
  type:
    | 'related-to'
    | 'teacher-of'
    | 'parent-of'
    | 'sibling-of'
    | 'friend-of'
    | 'enemy-of'
    | 'ally-of'
    | 'rival-of'
    | 'romantic-interest-of'
    | 'member-of'
    | 'leader-of'
    | 'owner-of'
    | 'user-of'
    | 'located-in'
    | 'participant-in';
  state?: ('unknown' | 'active' | 'ended') | null;
  /**
   * 1-based chapter number where this relation is established. Used for spoiler gating: hide the edge until the reader reaches this chapter.
   */
  chapterIndex?: number | null;
  note?: string | null;
  confidence?: number | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Bookkeeping for AI extraction runs: which chapter range was processed, with what model/prompt, and what it produced.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wikiIngestRuns".
 */
export interface WikiIngestRun {
  id: string;
  label: string;
  novel: string | Book;
  status: 'running' | 'completed' | 'partial' | 'failed';
  provider?: ('ollama' | 'vllm' | 'llama-cpp' | 'openai-compatible' | 'manual') | null;
  model?: string | null;
  startedAt?: string | null;
  finishedAt?: string | null;
  fromChapterIndex?: number | null;
  toChapterIndex?: number | null;
  /**
   * Chapter numbers within the range that failed and should be retried.
   */
  failedChapterIndexes?: number[] | null;
  processedChapters?: number | null;
  createdEntries?: number | null;
  updatedEntries?: number | null;
  createdMentions?: number | null;
  createdRelations?: number | null;
  promptVersion?: string | null;
  settings?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  error?: string | null;
  log?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'bookGenres';
        value: string | BookGenre;
      } | null)
    | ({
        relationTo: 'books';
        value: string | Book;
      } | null)
    | ({
        relationTo: 'authors';
        value: string | Author;
      } | null)
    | ({
        relationTo: 'bookChapters';
        value: string | BookChapter;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'readProgress';
        value: string | ReadProgress;
      } | null)
    | ({
        relationTo: 'chapterComments';
        value: string | ChapterComment;
      } | null)
    | ({
        relationTo: 'bookmarks';
        value: string | Bookmark;
      } | null)
    | ({
        relationTo: 'complaints';
        value: string | Complaint;
      } | null)
    | ({
        relationTo: 'reviews';
        value: string | Review;
      } | null)
    | ({
        relationTo: 'user-uploads';
        value: string | UserUpload;
      } | null)
    | ({
        relationTo: 'notifications';
        value: string | Notification;
      } | null)
    | ({
        relationTo: 'wikiEntries';
        value: string | WikiEntry;
      } | null)
    | ({
        relationTo: 'wikiMentions';
        value: string | WikiMention;
      } | null)
    | ({
        relationTo: 'wikiRelations';
        value: string | WikiRelation;
      } | null)
    | ({
        relationTo: 'wikiIngestRuns';
        value: string | WikiIngestRun;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  authStrategies?:
    | T
    | {
        providerUserId?: T;
        accessToken?: T;
        refreshToken?: T;
        tokenType?: T;
        idToken?: T;
        tokenExpiry?: T;
        authProvider?: T;
        id?: T;
      };
  nickname?: T;
  roles?: T;
  bookAccess?: T;
  avatar?: T;
  banner?: T;
  isPublic?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookGenres_select".
 */
export interface BookGenresSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books_select".
 */
export interface BooksSelect<T extends boolean = true> {
  _books_books_order?: T;
  _order?: T;
  title?: T;
  alternativeNames?: T;
  status?: T;
  coverImage?: T;
  description?: T;
  wikiContext?: T;
  genres?: T;
  chapters?: T;
  volumes?:
    | T
    | {
        name?: T;
        from?: T;
        to?: T;
        id?: T;
      };
  author?: T;
  slug?: T;
  slugLock?: T;
  chapterCount?: T;
  averageRating?: T;
  totalReviews?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  books?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookChapters_select".
 */
export interface BookChaptersSelect<T extends boolean = true> {
  _bookChapters_chapters_order?: T;
  title?: T;
  isSpoiler?: T;
  content?: T;
  addedAt?: T;
  book?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  shortDescription?: T;
  image?: T;
  content?: T;
  publishedAt?: T;
  slug?: T;
  slugLock?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "readProgress_select".
 */
export interface ReadProgressSelect<T extends boolean = true> {
  user?: T;
  book?: T;
  chapter?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chapterComments_select".
 */
export interface ChapterCommentsSelect<T extends boolean = true> {
  user?: T;
  chapter?: T;
  content?: T;
  children?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookmarks_select".
 */
export interface BookmarksSelect<T extends boolean = true> {
  user?: T;
  book?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "complaints_select".
 */
export interface ComplaintsSelect<T extends boolean = true> {
  selectedText?: T;
  complaintType?: T;
  description?: T;
  pageNumber?: T;
  chapter?: T;
  book?: T;
  position?:
    | T
    | {
        start?: T;
        end?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  user?: T;
  book?: T;
  content?: T;
  rating?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-uploads_select".
 */
export interface UserUploadsSelect<T extends boolean = true> {
  owner?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  user?: T;
  title?: T;
  message?: T;
  type?: T;
  read?: T;
  link?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wikiEntries_select".
 */
export interface WikiEntriesSelect<T extends boolean = true> {
  novel?: T;
  type?: T;
  title?: T;
  slug?: T;
  slugLock?: T;
  aliases?: T;
  image?: T;
  shortDescription?: T;
  content?: T;
  firstAppearanceIndex?: T;
  spoilerChapterIndex?: T;
  status?: T;
  confidence?: T;
  generatedBy?: T;
  lastProcessedChapterIndex?: T;
  metadata?: T;
  mentions?: T;
  outgoingRelations?: T;
  incomingRelations?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wikiMentions_select".
 */
export interface WikiMentionsSelect<T extends boolean = true> {
  novel?: T;
  entry?: T;
  chapter?: T;
  chapterIndex?: T;
  rawName?: T;
  mentionType?: T;
  quote?: T;
  context?: T;
  confidence?: T;
  approved?: T;
  source?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wikiRelations_select".
 */
export interface WikiRelationsSelect<T extends boolean = true> {
  novel?: T;
  sourceEntry?: T;
  targetEntry?: T;
  type?: T;
  state?: T;
  chapterIndex?: T;
  note?: T;
  confidence?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wikiIngestRuns_select".
 */
export interface WikiIngestRunsSelect<T extends boolean = true> {
  label?: T;
  novel?: T;
  status?: T;
  provider?: T;
  model?: T;
  startedAt?: T;
  finishedAt?: T;
  fromChapterIndex?: T;
  toChapterIndex?: T;
  failedChapterIndexes?: T;
  processedChapters?: T;
  createdEntries?: T;
  updatedEntries?: T;
  createdMentions?: T;
  createdRelations?: T;
  promptVersion?: T;
  settings?: T;
  error?: T;
  log?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banner".
 */
export interface Banner {
  id: string;
  enabled?: boolean | null;
  settings?: {
    /**
     * Unique identifier for the banner. Used to store user preferences for banner display. If you change this ID, all users will see the banner again.
     */
    uniqueID: string;
    /**
     * Text to be displayed in the banner. Supports: **bold** and *italic*.
     */
    text: string;
    isDismissible?: boolean | null;
    isLink?: boolean | null;
    linkSettings?: {
      url: string;
      buttonText: string;
      openInNewTab?: boolean | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banner_select".
 */
export interface BannerSelect<T extends boolean = true> {
  enabled?: T;
  settings?:
    | T
    | {
        uniqueID?: T;
        text?: T;
        isDismissible?: T;
        isLink?: T;
        linkSettings?:
          | T
          | {
              url?: T;
              buttonText?: T;
              openInNewTab?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ComparisonBlock".
 */
export interface ComparisonBlock {
  /**
   * Block title displayed under the comparison slider.
   */
  title?: string | null;
  /**
   * The image that will be shown on the left side of the slider.
   */
  leftImage: string | Media;
  /**
   * The image that will be shown on the right side of the slider.
   */
  rightImage: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'comparison-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}